### ISSUE TITLE
Question: Is there a way to enable SSL?

### ISSUE THREAD

**Issue by tadghh** [ginger51011/pandoras_pot#51]
Looked through main.rs and noticed Axum but didnt see anyway to add on an SSL cert. Ive tried using HAProxy infront of it and redirecting HTTP to HTTPS but its gaslighting me and saying "no service aval" (even though there is). So yeah is there any chance this will get SSL support/or has?

**Comment by ginger51011** [comment]
Thanks for taking the time to open an issue!

To answer the question in the title: **No, as of v0.6.2 there is no way to enable TLS/SSL termination directly in `pandoras_pot`**.

Let's split the question into two:

1. How to use `pandoras_pot` with HAProxy?
2. Should we add SSL support for pandoras_pot?

Q1 (How to use `pandoras_pot` with HAProxy):

If I understand you correctly, your current setup is

```
Internet --HTTPS--> HAProxy --HTTP--> pandoras_pot
```

I've never used HAProxy before, but this is pretty much identical to the setup I use (and what I had in mind when I created `pandoras_pot`).  So this _should_ work, but I am not quite sure why it doesn't. I'm not sure how your environment looks, but just to have a quick checklist:

- [ ] Can you reach `pandoras_pot` on the port it's using? You can just use `curl --head localhost:8080` for this
- [ ] If so, does it work with another reverse proxy? I'm using [Caddy](https://caddyserver.com/), but you could use nginx or Apache or anything else as well.

Q2 (Should we add SSL support for pandoras_pot):

I don't think it would be that much work to add support for providing your own certs, like in [this example](https://github.com/tokio-rs/axum/blob/main/examples/tls-rustls/src/main.rs) from Axum. However, this would require a new dependency (`axum-server`), as well as some refactoring in `main.rs`. It would also require some more configuration options and error handling. Also, as of now, `pandoras_pot` relies on being behind a reverse proxy that some logging (specifically IPs) rely on the reverse proxy setting some HTTP headers. This might just be bad design tbh.

Far from impossible, but not without cost.

Let's list some pros and cons for this; anyone reading this should feel free to chime in and add more to this list!

Pros:

- More control over certificates
- Easier setup (does not require reverse proxy)
- I know of some competitions where people place traps on hosts to mess with other teams, so setting `pandoras_pot` on port 443 directly might be a use case?
- Performance: it might become easier to benchmark if we do everything in `pandoras_pot`

Cons:

- More dependencies that might be unused for a lot of people
- Maintenance cost
- Handling certificates yourself requires know-how on the users part, and you can mess it up
- Security considerations; security is hard!
- Breaking the Unix philosophy: Should `pandoras_pot` really be considering HTTPS, or should it just serve a valid but twisted HTTP response on a port?

**Comment by ginger51011** [comment]
Another thing to consider: If `pandoras_pot` is used without a reverse proxy in front of it, what should it set the `Server` header to? I thinl HellPot has a config option for this.

**Comment by tadghh** [comment]
So after thinking it over for a bit I think its that I cant get HAProxy to upgrade the HTTP requests. Anyhow incase im overlooking something

### build cfg
```cfg
[http]
port = "443"
routes = ["/wp-login.php", "/.env","/.git","/confidential","/admin","/private","/logs","/db_backup.sql","/backup"]
catch_all = false
rate_limit = 0
rate_limit_period = 300 # 5 minutes
health_port_enabled = false
health_port = "8081"
content_type = "text/html; charset=utf-8"

[generator]
chunk_size = 16384 # 1024 * 16
type = { name = "random" }
max_concurrent = 100
time_limit = 0
size_limit = 0
chunk_buffer = 250
prefix = "<!DOCTYPE html><html><body>"

[logging]
output_path = "pandoras.log"
print_pretty_logs = true
no_stdout = false
```

### Deployment and service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: pandoras-pot-service
spec:
  selector:
    app: pandoras-pot
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandoras-pot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pandoras-pot
  template:
    metadata:
      labels:
        app: pandoras-pot
    spec:
      containers:
      - name: pandoras-pot
        image: localhost:5000/pandoras_p3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 443
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /wp-login.php
            port: 443
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
```

- My readiness probe is responding so I know its up and working

### HAProxy ingress
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustblog-ingress
  labels:
     app: rustblog
  annotations:
    ingress.class: "haproxy"
    haproxy.org/server-ssl: "true"
    # haproxy.org/ssl-passthrough: "true" 
    # haproxy.org/ssl-redirect: "true"
    # haproxy.org/ssl-redirect-port: "443"
spec:
  ingressClassName: haproxy
  rules:
   - host: "tadgh.dev"
     http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
           service: 
             name: rustblog-service
             port:
               number: 443
      - path: /wp-login.php
        pathType: Prefix
        backend: 
           service: 
             name: pandoras-pot-service
             port:
               number: 443
```

Im using cloudflare to manage my domain and have http -> https setup. When hitting my /wp-login path I get `HAproxy 503 Service Unavailable No server is available to handle this request` which I think is because of pandora not using https (but we know pandora is working because the readiness probe). If it looks like I might be overlooking something lmk!

Overall this looks like a me problem but adding SSL support would be a huge help + increase the tools accessibility.

**Comment by tadghh** [comment]
1. Yeah I understand that, if I were to move forward without HTTPS it wouldnt make sense to me. All of my site uses SSL except for the paths made for robots.txt? 
2. Below is me running the image on localhost with the port changed to 6688
![image](https://github.com/user-attachments/assets/1bf3ea0a-9263-4740-875f-83847dc7dae4)
![image](https://github.com/user-attachments/assets/ee80fd7e-19f7-4053-8b32-ed97094c2f1d)

3. I suppose, theres no issue in the logs otherwise (pandora.log) doesnt have any error looking things printed in it.
4. These are the docs im using ATM
	https://www.haproxy.com/documentation/kubernetes-ingress/ingress-tutorials/terminate-ssl/
	https://github.com/haproxytech/helm-charts
5. Sure that would work I had it like that while testing earlier. Idk I think im just having skill issues with this. If you can somehow get everything working on HTTPS that would work great for my scenario since im using cloudflare to forware http -> https

Thanks for helping so far, no pressure. Im going to take a look at this later.

**Comment by ginger51011** [comment]
Thanks for linking the docs at 4, that helps!

I looked a bit at the docs and still have a question. I understand it as this is the structure you want (correct me if I'm wrong!):

```mermaid
graph LR
 Internet -->|HTTPS| Ingress
 Ingress -->|HTTPS| Rustblog
 subgraph Cert 1
  Rustblog
 end
 Ingress -->|HTTPS| pandoras_pot
 subgraph Cert 2
  pandoras_pot
 end
```

The structure I usually use is the following

```mermaid
graph LR
 Internet -->|HTTPS| Ingress
 Ingress -->|HTTP| Rustblog
 subgraph Cert
  Ingress
 end
 Ingress -->|HTTP| pandoras_pot
```

I think this can be achieved using the strategy for HAProxy [here](https://www.haproxy.com/documentation/kubernetes-ingress/ingress-tutorials/terminate-ssl/#configure-a-tls-certificate-for-an-ingress-rule), i.e.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustblog-ingress
  labels:
     app: rustblog
spec:
  ingressClassName: haproxy
  tls:
  - secretName: example-cert # CHANGE ME :D
    hosts:
    - "tadgh.dev"
  rules:
   - host: "tadgh.dev"
     http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
           service: 
             name: rustblog-service
             port:
               number: 8080 # I am some random HTTP port
      - path: /wp-login.php
        pathType: Prefix
        backend: 
           service: 
             name: pandoras-pot-service
             port:
               number: 8081 # So am I
```

Looking at the docs, there are many different ways to solve this. Perhaps you can let your rustblog-service use its own cert, but provide one for pandoras-pot-service :shrug: 

I'm not going into the implication about having HTTP _inside_ the cluster; I'm unsure of what best practices might be. If you are running the whole cluster in a single host, this should be fine. However, I suppose you point your whole domain (tagdh.dev) at your ingress?

Quick note on 3: It might be the case that a readiness check is just a HEAD request. Either way, the health port was implemented for this usecase. Then you must use `health_port_enabled = true` and open the port though :)

**Comment by tadghh** [comment]
> Thanks for linking the docs at 4, that helps!
> 
> I looked a bit at the docs and still have a question. I understand it as this is the structure you want (correct me if I'm wrong!):
> 
> ```mermaid
> graph LR
>  Internet -->|HTTPS| Ingress
>  Ingress -->|HTTPS| Rustblog
>  subgraph Cert 1
>   Rustblog
>  end
>  Ingress -->|HTTPS| pandoras_pot
>  subgraph Cert 2
>   pandoras_pot
>  end
> ```
> 
> The structure I usually use is the following
> 
> ```mermaid
> graph LR
>  Internet -->|HTTPS| Ingress
>  Ingress -->|HTTP| Rustblog
>  subgraph Cert
>   Ingress
>  end
>  Ingress -->|HTTP| pandoras_pot
> ```
> 
> I think this can be achieved using the strategy for HAProxy [here](https://www.haproxy.com/documentation/kubernetes-ingress/ingress-tutorials/terminate-ssl/#configure-a-tls-certificate-for-an-ingress-rule), i.e.
> 
> ```yaml
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: rustblog-ingress
>   labels:
>      app: rustblog
> spec:
>   ingressClassName: haproxy
>   tls:
>   - secretName: example-cert # CHANGE ME :D
>     hosts:
>     - "tadgh.dev"
>   rules:
>    - host: "tadgh.dev"
>      http:
>       paths:
>       - path: /
>         pathType: Prefix
>         backend: 
>            service: 
>              name: rustblog-service
>              port:
>                number: 8080 # I am some random HTTP port
>       - path: /wp-login.php
>         pathType: Prefix
>         backend: 
>            service: 
>              name: pandoras-pot-service
>              port:
>                number: 8081 # So am I
> ```
> 
> Looking at the docs, there are many different ways to solve this. Perhaps you can let your rustblog-service use its own cert, but provide one for pandoras-pot-service 🤷
> 
> I'm not going into the implication about having HTTP _inside_ the cluster; I'm unsure of what best practices might be. If you are running the whole cluster in a single host, this should be fine. However, I suppose you point your whole domain (tagdh.dev) at your ingress?
> 
> Quick note on 3: It might be the case that a readiness check is just a HEAD request. Either way, the health port was implemented for this usecase. Then you must use `health_port_enabled = true` and open the port though :)


Thanks for this, those graphics are pretty much spot on. Im using rustls for my blog just 'because'. Ill setup a minikube enviroment when I have time to verify my issue. Your example should work its just that HAProxy says it cant find the server (pandoras_pot) which I think is because it "expects" it to be https. Thanks for helping so far though!

**Comment by tadghh** [comment]
Big ups got it! :) I needed to make two seperate ingress resources

```yaml
# Main site, with backend services that handle ssl
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lying-ingress
  labels:
     app: female-dog
  annotations:
    ingress.class: "haproxy"
    haproxy.org/server-ssl: "true"
    # haproxy.org/ssl-passthrough: "true" 
    # haproxy.org/ssl-redirect: "true"
    # haproxy.org/ssl-redirect-port: "443"
spec:
  ingressClassName: haproxy
  rules:
  - host: "localhost"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
           service: 
             name: rustblog-service
             port:
               number: 443
      - path: /ruby/
        pathType: Prefix
        backend: 
           service: 
             name: rubycomp-service  
             port:
               number: 443
      - path: /rubys/
        pathType: Prefix
        backend: 
           service: 
             name: rubycomp-service  
             port:
               number: 443


```

```yaml 
# http backend service -> https frontend
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pot-ingress
  labels:
    app: female-dog
  annotations:
    ingress.class: "haproxy"
    haproxy.org/server-ssl: "false"  # Explicitly disable server SSL for this service
spec:
  ingressClassName: haproxy
  rules:
  - host: "localhost"
    http:
      paths:
      - path: /wp-login.php
        pathType: Exact 
        backend: 
           service: 
             name: pot-service  
             port:
               number: 443  # Docker image was built using 443, along with config file
```

The main difference is disabling haproxy/server-ssl on the http pandora backend. My networking know how is a bit wavey but im able to trigger pandora at https! so somehow the http traffic is being upgraded, or perhaps our tls cert gives us authority to spew out whatever through the "secure window" (tls | https | crt stuff?)
